version: "3"
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    networks:
      - grafana
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
networks:
  grafana:
    external: true
