version: '3'
services:
  ddns-go:
    image: jeessy/ddns-go:latest
    container_name: ddns-go
    restart: always
    ports:
      - 9876:9876
    volumes:
            - /home/rguo/apps/ddns:/root
    network_mode: "host"

