version: '3'
services:
  redis:
    restart: always
    image: redis:latest
    container_name: redis
    volumes:
        # - /etc/localtime:etc/localtime
    ports:
      # 宿主机：容器
      - 6379:6379
    expose:
      - 6379
    networks:
      - db
networks:
  db:
    external: true
